import type { Blueprint } from "./types";

export function blueprintToMarkdown(bp: Blueprint, idea: string): string {
  const lines: string[] = [];
  const o = bp.overview;

  lines.push(`# ${o.name}`);
  lines.push(`> ${o.tagline}\n`);
  lines.push(`**Идея:** ${idea}\n`);

  lines.push(`## Project Overview`);
  lines.push(`- **Описание:** ${o.description}`);
  lines.push(`- **Аудитория:** ${o.audience}`);
  lines.push(`- **Проблема:** ${o.problem}`);
  lines.push(`- **Решение:** ${o.solution}\n`);

  lines.push(`## Discovery`);
  lines.push(`- **Тип продукта:** ${bp.discovery.productType}`);
  lines.push(`- **Пользователи:** ${bp.discovery.targetUsers}`);
  lines.push(`- **Потенциал:** ${bp.discovery.potential}\n`);
  lines.push(`### Конкуренты`);
  for (const c of bp.discovery.competitors) {
    lines.push(`- **${c.name}** — ${c.description}`);
    lines.push(`  - Сильные стороны: ${c.strengths.join(", ")}`);
    lines.push(`  - Слабые стороны: ${c.weaknesses.join(", ")}`);
  }
  lines.push("");

  lines.push(`## Architecture`);
  for (const layer of bp.architecture) {
    lines.push(`### ${layer.layer}`);
    lines.push(`- Технологии: ${layer.technologies.join(", ")}`);
    lines.push(`- Почему: ${layer.reason}`);
  }
  lines.push("");

  lines.push(`## Database`);
  for (const t of bp.database) {
    lines.push(`### ${t.name}`);
    lines.push(`| Поле | Тип | Примечание |`);
    lines.push(`|------|-----|------------|`);
    for (const f of t.fields) lines.push(`| ${f.name} | ${f.type} | ${f.note ?? ""} |`);
    lines.push("");
  }

  lines.push(`## API`);
  lines.push(`| Метод | Путь | Описание |`);
  lines.push(`|-------|------|----------|`);
  for (const e of bp.api) lines.push(`| ${e.method} | \`${e.path}\` | ${e.description} |`);
  lines.push("");

  lines.push(`## Roadmap`);
  for (const p of bp.roadmap) {
    lines.push(`### ${p.phase}: ${p.title} (${p.duration})`);
    for (const t of p.tasks) lines.push(`- [ ] ${t}`);
    lines.push("");
  }

  lines.push(`## Project Score`);
  lines.push(`- Innovation: **${bp.score.innovation}/100**`);
  lines.push(`- Difficulty: **${bp.score.difficulty}/100**`);
  lines.push(`- Market Potential: **${bp.score.market}/100**`);
  lines.push(`- Development Cost: **${bp.score.cost}**`);
  lines.push(`- Risk Level: **${bp.score.risk}**`);
  lines.push(`\n${bp.score.explanation}\n`);

  lines.push(`## AI Critic`);
  for (const c of bp.critique) lines.push(`- ⚠ ${c}`);
  lines.push("");

  lines.push(`## Risks`);
  for (const r of bp.risks) lines.push(`- **[${r.severity}] ${r.risk}** — ${r.mitigation}`);
  lines.push("");
  lines.push(`---`);
  lines.push(`*Generated by Atrion 2.0 — AI Software Architect*`);

  return lines.join("\n");
}

export function download(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
