"use client";
import { useRef, useState } from "react";
import type { Rig2DDocument } from "@/shared/rigging/rig2d";
import { captureKeyform, sampleKeyforms, type Parameter2D } from "@/shared/rigging/parameters";

const button="rounded-lg border border-white/20 px-3 py-2 text-xs disabled:opacity-40";
const input="w-full rounded-lg border border-white/20 bg-[#211f2e] p-2 text-sm";
export default function ParameterPanel({document,authoring,values,clipId,time,onTime,onAuthor,onChange,onPreview,onPlay}:{document:Rig2DDocument;authoring:string;values?:Record<string,number>;clipId?:string;time:number;onTime:(time:number)=>void;onAuthor:(id:string)=>void;onChange:(edit:(doc:Rig2DDocument)=>void)=>boolean;onPreview:(doc:Rig2DDocument|null)=>void;onPlay:(clipId:string)=>void}){
  const [selected,setSelected]=useState(''),[target,setTarget]=useState(''),[name,setName]=useState('Наклон');
  const [range,setRange]=useState({min:-30,max:30,initial:0});
  const parameters=document.parameters??[],parameter=parameters.find(p=>p.id===selected),deformers=document.deformers??[];
  const drag=useRef<{id:string;value:number}|null>(null);
  const [dragValue,setDragValue]=useState<number|null>(null);
  const visibleValue=parameter?(dragValue??values?.[parameter.id]??parameter.value):0;
  const clip=document.clips.find(c=>c.id===clipId),track=clip?.parameterTracks?.find(t=>t.parameterId===parameter?.id);
  const [interpolation,setInterpolation]=useState<'linear'|'step'>('linear');
  function setValue(p:Parameter2D,value:number){onChange(doc=>{doc.parameters!.find(v=>v.id===p.id)!.value=value;});}
  function previewValue(p:Parameter2D,value:number){if(!drag.current){setValue(p,value);return;}setDragValue(value);drag.current.value=value;onPreview({...document,parameters:parameters.map(v=>v.id===p.id?{...v,value}:v)});}
  function finish(cancel=false){const active=drag.current;drag.current=null;if(!active)return;setDragValue(null);onPreview(null);if(!cancel){const p=parameters.find(p=>p.id===active.id)!;if(p.value!==active.value)setValue(p,active.value);}}
  function author(p:Parameter2D,value:number){const shape=sampleKeyforms(p,value);if(onChange(doc=>{const d=doc.deformers!.find(d=>d.id===p.deformerId)!;Object.assign(d,{position:[...shape.position],scale:[...shape.scale],rotation:shape.rotation,...(d.kind==='warp'?{points:shape.points!.map(p=>[...p])}:{})});doc.parameters!.find(v=>v.id===p.id)!.value=value;}))onAuthor(p.id);}
  return <section aria-label="Параметры и ключевые формы" className="space-y-3 rounded-xl border border-violet-300/25 p-4">
    <h2 className="text-sm font-semibold">Параметры и ключевые формы</h2>
    <p className="text-xs text-white/55">Параметр плавно смешивает формы одного деформера. Для сочетания независимых движений используйте вложенные деформеры.</p>
    <div className="grid gap-2 sm:grid-cols-2"><input aria-label="Название параметра" className={input} value={name} onChange={e=>setName(e.target.value)}/><select aria-label="Деформер нового параметра" className={input} value={target} onChange={e=>setTarget(e.target.value)}><option value="">Выберите деформер</option>{deformers.filter(d=>!parameters.some(p=>p.deformerId===d.id)).map(d=><option key={d.id} value={d.id}>{d.kind==='warp'?'Warp':'Поворот'} {deformers.indexOf(d)+1}</option>)}</select></div>
    <div className="flex flex-wrap items-end gap-2">{([['min','Минимум'],['max','Максимум'],['initial','По умолчанию']] as const).map(([key,label])=><label key={key} className="text-xs">{label}<input aria-label={`${label} параметра`} className={`${input} !w-28`} type="number" value={range[key]} onChange={e=>setRange({...range,[key]:Number(e.target.value)})}/></label>)}<button className={button} disabled={!target||!name.trim()} onClick={()=>{const d=deformers.find(d=>d.id===target);if(!d)return;const id=`param_${crypto.randomUUID()}`;if(onChange(doc=>{doc.parameters??=[];doc.parameters.push({id,name,min:range.min,max:range.max,default:range.initial,value:range.initial,deformerId:d.id,keyforms:[captureKeyform(d,range.initial)]});})){setSelected(id);setTarget('');}}}>Создать параметр</button></div>
    <select aria-label="Параметр" className={input} value={parameter?.id??''} onChange={e=>{onAuthor('');setSelected(e.target.value);}}><option value="">Выберите параметр</option>{parameters.map(p=><option key={p.id} value={p.id}>{p.name} · {p.keyforms.length} форм</option>)}</select>
    {parameter&&<>
      <label className="flex items-center gap-3 text-sm"><span>{parameter.name}</span><input aria-label="Значение параметра" className="min-w-0 flex-1 accent-violet-400" type="range" min={parameter.min} max={parameter.max} step={(parameter.max-parameter.min)/200} value={visibleValue} disabled={!!authoring} onPointerDown={()=>{drag.current={id:parameter.id,value:visibleValue};}} onChange={e=>previewValue(parameter,Number(e.target.value))} onPointerUp={()=>finish()} onPointerCancel={()=>finish(true)} onBlur={()=>finish()} /><output>{visibleValue.toFixed(2)}</output></label>
      <div className="flex flex-wrap gap-2">{[parameter.min,parameter.default,parameter.max].map((v,i)=><button key={i} className={button} onClick={()=>{onAuthor('');setValue(parameter,v);}}>{v}</button>)}<button className={button} onClick={()=>author(parameter,visibleValue)}>Править форму в этом значении</button></div>
      {parameter.keyforms.length===1&&<p className="text-xs text-amber-200">Пока сохранена одна форма. Добавьте другую форму, чтобы ползунок менял изображение.</p>}
      {!!authoring&&<div className="space-y-2 rounded-lg bg-violet-400/10 p-3"><p className="text-xs">Редактируйте выбранный деформер ниже, затем сохраните форму в значении {parameter.value}. Изменения исходного деформера тоже входят в историю. Центр и родитель общие для всех форм.</p><button className={button} onClick={()=>{if(onChange(doc=>{const p=doc.parameters!.find(p=>p.id===parameter.id)!,d=doc.deformers!.find(d=>d.id===p.deformerId)!;p.keyforms=[...p.keyforms.filter(k=>k.value!==p.value),captureKeyform(d,p.value)].sort((a,b)=>a.value-b.value);})){onAuthor('');}}}>Сохранить ключевую форму</button><button className={`${button} ml-2`} onClick={()=>onAuthor('')}>Просмотр параметра</button></div>}
      <div className="flex flex-wrap gap-2">{parameter.keyforms.map(k=><button className={button} key={k.value} onClick={()=>author(parameter,k.value)}>Форма {k.value}</button>)}</div>
      {clip&&<div className="space-y-2 border-t border-white/10 pt-3"><p className="text-xs">Ключи параметра в выбранном клипе · {time.toFixed(2)} с</p><div className="flex flex-wrap gap-2"><select aria-label="Интерполяция параметра" className={`${input} !w-36`} value={interpolation} onChange={e=>setInterpolation(e.target.value as 'linear'|'step')}><option value="linear">Плавная</option><option value="step">Ступенчатая</option></select><button className={button} disabled={!!authoring} onClick={()=>onChange(doc=>{const c=doc.clips.find(c=>c.id===clip.id)!;c.parameterTracks??=[];let t=c.parameterTracks.find(t=>t.parameterId===parameter.id);if(!t){t={parameterId:parameter.id,keys:[]};c.parameterTracks.push(t);}t.keys=[...t.keys.filter(k=>Math.abs(k.time-time)>1e-6),{time,value:visibleValue,interpolation}].sort((a,b)=>a.time-b.time);})}>+ Ключ параметра</button><button className={button} disabled={!track?.keys.some(k=>Math.abs(k.time-time)<1e-6)} onClick={()=>onChange(doc=>{const c=doc.clips.find(c=>c.id===clip.id)!;const t=c.parameterTracks!.find(t=>t.parameterId===parameter.id)!;t.keys=t.keys.filter(k=>Math.abs(k.time-time)>1e-6);c.parameterTracks=c.parameterTracks!.filter(t=>t.keys.length);})}>Удалить ключ параметра</button></div><div className="flex flex-wrap gap-2">{track?.keys.map(k=><button key={k.time} className={button} onClick={()=>onTime(k.time)}>{k.time.toFixed(2)} с → {k.value.toFixed(2)}</button>)}</div></div>}
      <div className="flex flex-wrap gap-2"><button className={button} disabled={parameter.value===parameter.default||!parameter.keyforms.some(k=>k.value===parameter.value)} onClick={()=>onChange(doc=>{const p=doc.parameters!.find(p=>p.id===parameter.id)!;p.keyforms=p.keyforms.filter(k=>k.value!==p.value);})}>Удалить форму в этом значении</button><button className={button} disabled={parameter.keyforms.length<2} onClick={()=>{
        const clipId=`parameter_motion_${parameter.id}`;
        if(onChange(doc=>{const p=doc.parameters!.find(p=>p.id===parameter.id)!,low=p.keyforms[0].value,high=p.keyforms[p.keyforms.length-1].value;const clip={id:clipId,duration:4,loop:true,tracks:[],parameterTracks:[{parameterId:p.id,keys:[{time:0,value:low,interpolation:'linear' as const},{time:2,value:high,interpolation:'linear' as const},{time:4,value:low,interpolation:'linear' as const}]}]};doc.clips=[...doc.clips.filter(c=>c.id!==clipId),clip];})){onAuthor('');onPlay(clipId);}
      }}>Создать и проиграть цикл</button><button className={button} onClick={()=>{if(onChange(doc=>{doc.parameters=doc.parameters!.filter(p=>p.id!==parameter.id);for(const c of doc.clips)if(c.parameterTracks)c.parameterTracks=c.parameterTracks.filter(t=>t.parameterId!==parameter.id);})){onAuthor('');setSelected('');}}}>Удалить параметр</button></div>
    </>}
  </section>;
}
